# Generated by Django 6.0.3 on 2026-03-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='f_creaecion',
            new_name='f_creacion',
        ),
    ]
